version: "3.8"


services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: cidere
      POSTGRES_PASSWORD: cidere123
      POSTGRES_DB: cidere
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
 