version: "3.8"


services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cidere
      POSTGRES_PASSWORD: cidere123
      POSTGRES_DB: cidere
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  node:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres